/*
 * Box Platform API
 *
 * [Box Platform](https://box.dev) provides functionality to provide access to content stored within [Box](https://box.com). It provides endpoints for basic manipulation of files and folders, management of users within an enterprise, as well as more complex topics such as legal holds and retention policies.
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: devrel@box.com
 * Generated by: https://openapi-generator.tech
 */


use reqwest;

use crate::apis::ResponseContent;
use super::{Error, configuration};

/// struct for passing parameters to the method [`delete_retention_policy_assignments_id`]
#[derive(Clone, Debug, Default)]
pub struct DeleteRetentionPolicyAssignmentsIdParams {
    /// The ID of the retention policy assignment.
    pub retention_policy_assignment_id: String
}

/// struct for passing parameters to the method [`get_retention_policies_id_assignments`]
#[derive(Clone, Debug, Default)]
pub struct GetRetentionPoliciesIdAssignmentsParams {
    /// The ID of the retention policy.
    pub retention_policy_id: String,
    /// The type of the retention policy assignment to retrieve.
    pub r#type: Option<String>,
    /// A comma-separated list of attributes to include in the response. This can be used to request fields that are not normally returned in a standard response.  Be aware that specifying this parameter will have the effect that none of the standard fields are returned in the response unless explicitly specified, instead only fields for the mini representation are returned, additional to the fields requested.
    pub fields: Option<Vec<String>>,
    /// Defines the position marker at which to begin returning results. This is used when paginating using marker-based pagination.
    pub marker: Option<String>,
    /// The maximum number of items to return per page.
    pub limit: Option<i64>
}

/// struct for passing parameters to the method [`get_retention_policy_assignments_id`]
#[derive(Clone, Debug, Default)]
pub struct GetRetentionPolicyAssignmentsIdParams {
    /// The ID of the retention policy assignment.
    pub retention_policy_assignment_id: String,
    /// A comma-separated list of attributes to include in the response. This can be used to request fields that are not normally returned in a standard response.  Be aware that specifying this parameter will have the effect that none of the standard fields are returned in the response unless explicitly specified, instead only fields for the mini representation are returned, additional to the fields requested.
    pub fields: Option<Vec<String>>
}

/// struct for passing parameters to the method [`get_retention_policy_assignments_id_file_versions_under_retention`]
#[derive(Clone, Debug, Default)]
pub struct GetRetentionPolicyAssignmentsIdFileVersionsUnderRetentionParams {
    /// The ID of the retention policy assignment.
    pub retention_policy_assignment_id: String,
    /// Defines the position marker at which to begin returning results. This is used when paginating using marker-based pagination.  This requires `usemarker` to be set to `true`.
    pub marker: Option<String>,
    /// The maximum number of items to return per page.
    pub limit: Option<i64>
}

/// struct for passing parameters to the method [`get_retention_policy_assignments_id_files_under_retention`]
#[derive(Clone, Debug, Default)]
pub struct GetRetentionPolicyAssignmentsIdFilesUnderRetentionParams {
    /// The ID of the retention policy assignment.
    pub retention_policy_assignment_id: String,
    /// Defines the position marker at which to begin returning results. This is used when paginating using marker-based pagination.  This requires `usemarker` to be set to `true`.
    pub marker: Option<String>,
    /// The maximum number of items to return per page.
    pub limit: Option<i64>
}

/// struct for passing parameters to the method [`post_retention_policy_assignments`]
#[derive(Clone, Debug, Default)]
pub struct PostRetentionPolicyAssignmentsParams {
    pub post_retention_policy_assignments_request: Option<crate::models::PostRetentionPolicyAssignmentsRequest>
}


/// struct for typed errors of method [`delete_retention_policy_assignments_id`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum DeleteRetentionPolicyAssignmentsIdError {
    Status403(crate::models::ClientError),
    Status404(crate::models::ClientError),
    DefaultResponse(crate::models::ClientError),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`get_retention_policies_id_assignments`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum GetRetentionPoliciesIdAssignmentsError {
    Status400(crate::models::ClientError),
    DefaultResponse(crate::models::ClientError),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`get_retention_policy_assignments_id`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum GetRetentionPolicyAssignmentsIdError {
    DefaultResponse(crate::models::ClientError),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`get_retention_policy_assignments_id_file_versions_under_retention`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum GetRetentionPolicyAssignmentsIdFileVersionsUnderRetentionError {
    Status400(crate::models::ClientError),
    DefaultResponse(crate::models::ClientError),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`get_retention_policy_assignments_id_files_under_retention`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum GetRetentionPolicyAssignmentsIdFilesUnderRetentionError {
    Status400(crate::models::ClientError),
    DefaultResponse(crate::models::ClientError),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`post_retention_policy_assignments`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum PostRetentionPolicyAssignmentsError {
    Status400(crate::models::ClientError),
    Status404(crate::models::ClientError),
    Status409(crate::models::ClientError),
    DefaultResponse(crate::models::ClientError),
    UnknownValue(serde_json::Value),
}


/// Removes a retention policy assignment applied to content.
pub async fn delete_retention_policy_assignments_id(configuration: &configuration::Configuration, params: DeleteRetentionPolicyAssignmentsIdParams) -> Result<(), Error<DeleteRetentionPolicyAssignmentsIdError>> {
    let local_var_configuration = configuration;

    // unbox the parameters
    let retention_policy_assignment_id = params.retention_policy_assignment_id;


    let local_var_client = &local_var_configuration.client;

    let local_var_uri_str = format!("{}/retention_policy_assignments/{retention_policy_assignment_id}", local_var_configuration.base_path, retention_policy_assignment_id=crate::apis::urlencode(retention_policy_assignment_id));
    let mut local_var_req_builder = local_var_client.request(reqwest::Method::DELETE, local_var_uri_str.as_str());

    if let Some(ref local_var_user_agent) = local_var_configuration.user_agent {
        local_var_req_builder = local_var_req_builder.header(reqwest::header::USER_AGENT, local_var_user_agent.clone());
    }
    if let Some(ref local_var_token) = local_var_configuration.oauth_access_token {
        local_var_req_builder = local_var_req_builder.bearer_auth(local_var_token.to_owned());
    };

    let local_var_req = local_var_req_builder.build()?;
    let local_var_resp = local_var_client.execute(local_var_req).await?;

    let local_var_status = local_var_resp.status();
    let local_var_content = local_var_resp.text().await?;

    if !local_var_status.is_client_error() && !local_var_status.is_server_error() {
        Ok(())
    } else {
        let local_var_entity: Option<DeleteRetentionPolicyAssignmentsIdError> = serde_json::from_str(&local_var_content).ok();
        let local_var_error = ResponseContent { status: local_var_status, content: local_var_content, entity: local_var_entity };
        Err(Error::ResponseError(local_var_error))
    }
}

/// Returns a list of all retention policy assignments associated with a specified retention policy.
pub async fn get_retention_policies_id_assignments(configuration: &configuration::Configuration, params: GetRetentionPoliciesIdAssignmentsParams) -> Result<crate::models::RetentionPolicyAssignments, Error<GetRetentionPoliciesIdAssignmentsError>> {
    let local_var_configuration = configuration;

    // unbox the parameters
    let retention_policy_id = params.retention_policy_id;
    let r#type = params.r#type;
    let fields = params.fields;
    let marker = params.marker;
    let limit = params.limit;


    let local_var_client = &local_var_configuration.client;

    let local_var_uri_str = format!("{}/retention_policies/{retention_policy_id}/assignments", local_var_configuration.base_path, retention_policy_id=crate::apis::urlencode(retention_policy_id));
    let mut local_var_req_builder = local_var_client.request(reqwest::Method::GET, local_var_uri_str.as_str());

    if let Some(ref local_var_str) = r#type {
        local_var_req_builder = local_var_req_builder.query(&[("type", &local_var_str.to_string())]);
    }
    if let Some(ref local_var_str) = fields {
        local_var_req_builder = match "csv" {
            "multi" => local_var_req_builder.query(&local_var_str.into_iter().map(|p| ("fields".to_owned(), p.to_string())).collect::<Vec<(std::string::String, std::string::String)>>()),
            _ => local_var_req_builder.query(&[("fields", &local_var_str.into_iter().map(|p| p.to_string()).collect::<Vec<String>>().join(",").to_string())]),
        };
    }
    if let Some(ref local_var_str) = marker {
        local_var_req_builder = local_var_req_builder.query(&[("marker", &local_var_str.to_string())]);
    }
    if let Some(ref local_var_str) = limit {
        local_var_req_builder = local_var_req_builder.query(&[("limit", &local_var_str.to_string())]);
    }
    if let Some(ref local_var_user_agent) = local_var_configuration.user_agent {
        local_var_req_builder = local_var_req_builder.header(reqwest::header::USER_AGENT, local_var_user_agent.clone());
    }
    if let Some(ref local_var_token) = local_var_configuration.oauth_access_token {
        local_var_req_builder = local_var_req_builder.bearer_auth(local_var_token.to_owned());
    };

    let local_var_req = local_var_req_builder.build()?;
    let local_var_resp = local_var_client.execute(local_var_req).await?;

    let local_var_status = local_var_resp.status();
    let local_var_content = local_var_resp.text().await?;

    if !local_var_status.is_client_error() && !local_var_status.is_server_error() {
        serde_json::from_str(&local_var_content).map_err(Error::from)
    } else {
        let local_var_entity: Option<GetRetentionPoliciesIdAssignmentsError> = serde_json::from_str(&local_var_content).ok();
        let local_var_error = ResponseContent { status: local_var_status, content: local_var_content, entity: local_var_entity };
        Err(Error::ResponseError(local_var_error))
    }
}

/// Retrieves a retention policy assignment
pub async fn get_retention_policy_assignments_id(configuration: &configuration::Configuration, params: GetRetentionPolicyAssignmentsIdParams) -> Result<crate::models::RetentionPolicyAssignment, Error<GetRetentionPolicyAssignmentsIdError>> {
    let local_var_configuration = configuration;

    // unbox the parameters
    let retention_policy_assignment_id = params.retention_policy_assignment_id;
    let fields = params.fields;


    let local_var_client = &local_var_configuration.client;

    let local_var_uri_str = format!("{}/retention_policy_assignments/{retention_policy_assignment_id}", local_var_configuration.base_path, retention_policy_assignment_id=crate::apis::urlencode(retention_policy_assignment_id));
    let mut local_var_req_builder = local_var_client.request(reqwest::Method::GET, local_var_uri_str.as_str());

    if let Some(ref local_var_str) = fields {
        local_var_req_builder = match "csv" {
            "multi" => local_var_req_builder.query(&local_var_str.into_iter().map(|p| ("fields".to_owned(), p.to_string())).collect::<Vec<(std::string::String, std::string::String)>>()),
            _ => local_var_req_builder.query(&[("fields", &local_var_str.into_iter().map(|p| p.to_string()).collect::<Vec<String>>().join(",").to_string())]),
        };
    }
    if let Some(ref local_var_user_agent) = local_var_configuration.user_agent {
        local_var_req_builder = local_var_req_builder.header(reqwest::header::USER_AGENT, local_var_user_agent.clone());
    }
    if let Some(ref local_var_token) = local_var_configuration.oauth_access_token {
        local_var_req_builder = local_var_req_builder.bearer_auth(local_var_token.to_owned());
    };

    let local_var_req = local_var_req_builder.build()?;
    let local_var_resp = local_var_client.execute(local_var_req).await?;

    let local_var_status = local_var_resp.status();
    let local_var_content = local_var_resp.text().await?;

    if !local_var_status.is_client_error() && !local_var_status.is_server_error() {
        serde_json::from_str(&local_var_content).map_err(Error::from)
    } else {
        let local_var_entity: Option<GetRetentionPolicyAssignmentsIdError> = serde_json::from_str(&local_var_content).ok();
        let local_var_error = ResponseContent { status: local_var_status, content: local_var_content, entity: local_var_entity };
        Err(Error::ResponseError(local_var_error))
    }
}

/// Returns a list of file versions under retention for a retention policy assignment.
pub async fn get_retention_policy_assignments_id_file_versions_under_retention(configuration: &configuration::Configuration, params: GetRetentionPolicyAssignmentsIdFileVersionsUnderRetentionParams) -> Result<crate::models::FilesUnderRetention, Error<GetRetentionPolicyAssignmentsIdFileVersionsUnderRetentionError>> {
    let local_var_configuration = configuration;

    // unbox the parameters
    let retention_policy_assignment_id = params.retention_policy_assignment_id;
    let marker = params.marker;
    let limit = params.limit;


    let local_var_client = &local_var_configuration.client;

    let local_var_uri_str = format!("{}/retention_policy_assignments/{retention_policy_assignment_id}/file_versions_under_retention", local_var_configuration.base_path, retention_policy_assignment_id=crate::apis::urlencode(retention_policy_assignment_id));
    let mut local_var_req_builder = local_var_client.request(reqwest::Method::GET, local_var_uri_str.as_str());

    if let Some(ref local_var_str) = marker {
        local_var_req_builder = local_var_req_builder.query(&[("marker", &local_var_str.to_string())]);
    }
    if let Some(ref local_var_str) = limit {
        local_var_req_builder = local_var_req_builder.query(&[("limit", &local_var_str.to_string())]);
    }
    if let Some(ref local_var_user_agent) = local_var_configuration.user_agent {
        local_var_req_builder = local_var_req_builder.header(reqwest::header::USER_AGENT, local_var_user_agent.clone());
    }
    if let Some(ref local_var_token) = local_var_configuration.oauth_access_token {
        local_var_req_builder = local_var_req_builder.bearer_auth(local_var_token.to_owned());
    };

    let local_var_req = local_var_req_builder.build()?;
    let local_var_resp = local_var_client.execute(local_var_req).await?;

    let local_var_status = local_var_resp.status();
    let local_var_content = local_var_resp.text().await?;

    if !local_var_status.is_client_error() && !local_var_status.is_server_error() {
        serde_json::from_str(&local_var_content).map_err(Error::from)
    } else {
        let local_var_entity: Option<GetRetentionPolicyAssignmentsIdFileVersionsUnderRetentionError> = serde_json::from_str(&local_var_content).ok();
        let local_var_error = ResponseContent { status: local_var_status, content: local_var_content, entity: local_var_entity };
        Err(Error::ResponseError(local_var_error))
    }
}

/// Returns a list of files under retention for a retention policy assignment.
pub async fn get_retention_policy_assignments_id_files_under_retention(configuration: &configuration::Configuration, params: GetRetentionPolicyAssignmentsIdFilesUnderRetentionParams) -> Result<crate::models::FilesUnderRetention, Error<GetRetentionPolicyAssignmentsIdFilesUnderRetentionError>> {
    let local_var_configuration = configuration;

    // unbox the parameters
    let retention_policy_assignment_id = params.retention_policy_assignment_id;
    let marker = params.marker;
    let limit = params.limit;


    let local_var_client = &local_var_configuration.client;

    let local_var_uri_str = format!("{}/retention_policy_assignments/{retention_policy_assignment_id}/files_under_retention", local_var_configuration.base_path, retention_policy_assignment_id=crate::apis::urlencode(retention_policy_assignment_id));
    let mut local_var_req_builder = local_var_client.request(reqwest::Method::GET, local_var_uri_str.as_str());

    if let Some(ref local_var_str) = marker {
        local_var_req_builder = local_var_req_builder.query(&[("marker", &local_var_str.to_string())]);
    }
    if let Some(ref local_var_str) = limit {
        local_var_req_builder = local_var_req_builder.query(&[("limit", &local_var_str.to_string())]);
    }
    if let Some(ref local_var_user_agent) = local_var_configuration.user_agent {
        local_var_req_builder = local_var_req_builder.header(reqwest::header::USER_AGENT, local_var_user_agent.clone());
    }
    if let Some(ref local_var_token) = local_var_configuration.oauth_access_token {
        local_var_req_builder = local_var_req_builder.bearer_auth(local_var_token.to_owned());
    };

    let local_var_req = local_var_req_builder.build()?;
    let local_var_resp = local_var_client.execute(local_var_req).await?;

    let local_var_status = local_var_resp.status();
    let local_var_content = local_var_resp.text().await?;

    if !local_var_status.is_client_error() && !local_var_status.is_server_error() {
        serde_json::from_str(&local_var_content).map_err(Error::from)
    } else {
        let local_var_entity: Option<GetRetentionPolicyAssignmentsIdFilesUnderRetentionError> = serde_json::from_str(&local_var_content).ok();
        let local_var_error = ResponseContent { status: local_var_status, content: local_var_content, entity: local_var_entity };
        Err(Error::ResponseError(local_var_error))
    }
}

/// Assigns a retention policy to an item.
pub async fn post_retention_policy_assignments(configuration: &configuration::Configuration, params: PostRetentionPolicyAssignmentsParams) -> Result<crate::models::RetentionPolicyAssignment, Error<PostRetentionPolicyAssignmentsError>> {
    let local_var_configuration = configuration;

    // unbox the parameters
    let post_retention_policy_assignments_request = params.post_retention_policy_assignments_request;


    let local_var_client = &local_var_configuration.client;

    let local_var_uri_str = format!("{}/retention_policy_assignments", local_var_configuration.base_path);
    let mut local_var_req_builder = local_var_client.request(reqwest::Method::POST, local_var_uri_str.as_str());

    if let Some(ref local_var_user_agent) = local_var_configuration.user_agent {
        local_var_req_builder = local_var_req_builder.header(reqwest::header::USER_AGENT, local_var_user_agent.clone());
    }
    if let Some(ref local_var_token) = local_var_configuration.oauth_access_token {
        local_var_req_builder = local_var_req_builder.bearer_auth(local_var_token.to_owned());
    };
    local_var_req_builder = local_var_req_builder.json(&post_retention_policy_assignments_request);

    let local_var_req = local_var_req_builder.build()?;
    let local_var_resp = local_var_client.execute(local_var_req).await?;

    let local_var_status = local_var_resp.status();
    let local_var_content = local_var_resp.text().await?;

    if !local_var_status.is_client_error() && !local_var_status.is_server_error() {
        serde_json::from_str(&local_var_content).map_err(Error::from)
    } else {
        let local_var_entity: Option<PostRetentionPolicyAssignmentsError> = serde_json::from_str(&local_var_content).ok();
        let local_var_error = ResponseContent { status: local_var_status, content: local_var_content, entity: local_var_entity };
        Err(Error::ResponseError(local_var_error))
    }
}

