/*
 * Box Platform API
 *
 * [Box Platform](https://box.dev) provides functionality to provide access to content stored within [Box](https://box.com). It provides endpoints for basic manipulation of files and folders, management of users within an enterprise, as well as more complex topics such as legal holds and retention policies.
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: devrel@box.com
 * Generated by: https://openapi-generator.tech
 */


use reqwest;

use crate::apis::ResponseContent;
use super::{Error, configuration};

/// struct for passing parameters to the method [`get_shield_information_barriers`]
#[derive(Clone, Debug, Default)]
pub struct GetShieldInformationBarriersParams {
    /// Defines the position marker at which to begin returning results. This is used when paginating using marker-based pagination.  This requires `usemarker` to be set to `true`.
    pub marker: Option<String>,
    /// The maximum number of items to return per page.
    pub limit: Option<i64>
}

/// struct for passing parameters to the method [`get_shield_information_barriers_id`]
#[derive(Clone, Debug, Default)]
pub struct GetShieldInformationBarriersIdParams {
    /// The ID of the shield information barrier.
    pub shield_information_barrier_id: String
}

/// struct for passing parameters to the method [`post_shield_information_barriers`]
#[derive(Clone, Debug, Default)]
pub struct PostShieldInformationBarriersParams {
    pub shield_information_barrier: Option<crate::models::ShieldInformationBarrier>
}

/// struct for passing parameters to the method [`post_shield_information_barriers_change_status`]
#[derive(Clone, Debug, Default)]
pub struct PostShieldInformationBarriersChangeStatusParams {
    pub post_shield_information_barriers_change_status_request: Option<crate::models::PostShieldInformationBarriersChangeStatusRequest>
}


/// struct for typed errors of method [`get_shield_information_barriers`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum GetShieldInformationBarriersError {
    Status404(crate::models::ClientError),
    DefaultResponse(crate::models::ClientError),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`get_shield_information_barriers_id`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum GetShieldInformationBarriersIdError {
    Status404(crate::models::ClientError),
    DefaultResponse(crate::models::ClientError),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`post_shield_information_barriers`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum PostShieldInformationBarriersError {
    Status404(crate::models::ClientError),
    DefaultResponse(crate::models::ClientError),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`post_shield_information_barriers_change_status`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum PostShieldInformationBarriersChangeStatusError {
    Status404(crate::models::ClientError),
    Status409(crate::models::ClientError),
    DefaultResponse(crate::models::ClientError),
    UnknownValue(serde_json::Value),
}


/// Retrieves a list of shield information barrier objects for the enterprise of JWT.
pub async fn get_shield_information_barriers(configuration: &configuration::Configuration, params: GetShieldInformationBarriersParams) -> Result<crate::models::GetShieldInformationBarriers200Response, Error<GetShieldInformationBarriersError>> {
    let local_var_configuration = configuration;

    // unbox the parameters
    let marker = params.marker;
    let limit = params.limit;


    let local_var_client = &local_var_configuration.client;

    let local_var_uri_str = format!("{}/shield_information_barriers", local_var_configuration.base_path);
    let mut local_var_req_builder = local_var_client.request(reqwest::Method::GET, local_var_uri_str.as_str());

    if let Some(ref local_var_str) = marker {
        local_var_req_builder = local_var_req_builder.query(&[("marker", &local_var_str.to_string())]);
    }
    if let Some(ref local_var_str) = limit {
        local_var_req_builder = local_var_req_builder.query(&[("limit", &local_var_str.to_string())]);
    }
    if let Some(ref local_var_user_agent) = local_var_configuration.user_agent {
        local_var_req_builder = local_var_req_builder.header(reqwest::header::USER_AGENT, local_var_user_agent.clone());
    }
    if let Some(ref local_var_token) = local_var_configuration.oauth_access_token {
        local_var_req_builder = local_var_req_builder.bearer_auth(local_var_token.to_owned());
    };

    let local_var_req = local_var_req_builder.build()?;
    let local_var_resp = local_var_client.execute(local_var_req).await?;

    let local_var_status = local_var_resp.status();
    let local_var_content = local_var_resp.text().await?;

    if !local_var_status.is_client_error() && !local_var_status.is_server_error() {
        serde_json::from_str(&local_var_content).map_err(Error::from)
    } else {
        let local_var_entity: Option<GetShieldInformationBarriersError> = serde_json::from_str(&local_var_content).ok();
        let local_var_error = ResponseContent { status: local_var_status, content: local_var_content, entity: local_var_entity };
        Err(Error::ResponseError(local_var_error))
    }
}

/// Get shield information barrier based on provided ID..
pub async fn get_shield_information_barriers_id(configuration: &configuration::Configuration, params: GetShieldInformationBarriersIdParams) -> Result<crate::models::ShieldInformationBarrier, Error<GetShieldInformationBarriersIdError>> {
    let local_var_configuration = configuration;

    // unbox the parameters
    let shield_information_barrier_id = params.shield_information_barrier_id;


    let local_var_client = &local_var_configuration.client;

    let local_var_uri_str = format!("{}/shield_information_barriers/{shield_information_barrier_id}", local_var_configuration.base_path, shield_information_barrier_id=crate::apis::urlencode(shield_information_barrier_id));
    let mut local_var_req_builder = local_var_client.request(reqwest::Method::GET, local_var_uri_str.as_str());

    if let Some(ref local_var_user_agent) = local_var_configuration.user_agent {
        local_var_req_builder = local_var_req_builder.header(reqwest::header::USER_AGENT, local_var_user_agent.clone());
    }
    if let Some(ref local_var_token) = local_var_configuration.oauth_access_token {
        local_var_req_builder = local_var_req_builder.bearer_auth(local_var_token.to_owned());
    };

    let local_var_req = local_var_req_builder.build()?;
    let local_var_resp = local_var_client.execute(local_var_req).await?;

    let local_var_status = local_var_resp.status();
    let local_var_content = local_var_resp.text().await?;

    if !local_var_status.is_client_error() && !local_var_status.is_server_error() {
        serde_json::from_str(&local_var_content).map_err(Error::from)
    } else {
        let local_var_entity: Option<GetShieldInformationBarriersIdError> = serde_json::from_str(&local_var_content).ok();
        let local_var_error = ResponseContent { status: local_var_status, content: local_var_content, entity: local_var_entity };
        Err(Error::ResponseError(local_var_error))
    }
}

/// Creates a shield information barrier to separate individuals/groups within the same firm and prevents confidential information passing between them.
pub async fn post_shield_information_barriers(configuration: &configuration::Configuration, params: PostShieldInformationBarriersParams) -> Result<crate::models::ShieldInformationBarrier, Error<PostShieldInformationBarriersError>> {
    let local_var_configuration = configuration;

    // unbox the parameters
    let shield_information_barrier = params.shield_information_barrier;


    let local_var_client = &local_var_configuration.client;

    let local_var_uri_str = format!("{}/shield_information_barriers", local_var_configuration.base_path);
    let mut local_var_req_builder = local_var_client.request(reqwest::Method::POST, local_var_uri_str.as_str());

    if let Some(ref local_var_user_agent) = local_var_configuration.user_agent {
        local_var_req_builder = local_var_req_builder.header(reqwest::header::USER_AGENT, local_var_user_agent.clone());
    }
    if let Some(ref local_var_token) = local_var_configuration.oauth_access_token {
        local_var_req_builder = local_var_req_builder.bearer_auth(local_var_token.to_owned());
    };
    local_var_req_builder = local_var_req_builder.json(&shield_information_barrier);

    let local_var_req = local_var_req_builder.build()?;
    let local_var_resp = local_var_client.execute(local_var_req).await?;

    let local_var_status = local_var_resp.status();
    let local_var_content = local_var_resp.text().await?;

    if !local_var_status.is_client_error() && !local_var_status.is_server_error() {
        serde_json::from_str(&local_var_content).map_err(Error::from)
    } else {
        let local_var_entity: Option<PostShieldInformationBarriersError> = serde_json::from_str(&local_var_content).ok();
        let local_var_error = ResponseContent { status: local_var_status, content: local_var_content, entity: local_var_entity };
        Err(Error::ResponseError(local_var_error))
    }
}

/// Change status of shield information barrier with the specified ID.
pub async fn post_shield_information_barriers_change_status(configuration: &configuration::Configuration, params: PostShieldInformationBarriersChangeStatusParams) -> Result<crate::models::ShieldInformationBarrier, Error<PostShieldInformationBarriersChangeStatusError>> {
    let local_var_configuration = configuration;

    // unbox the parameters
    let post_shield_information_barriers_change_status_request = params.post_shield_information_barriers_change_status_request;


    let local_var_client = &local_var_configuration.client;

    let local_var_uri_str = format!("{}/shield_information_barriers/change_status", local_var_configuration.base_path);
    let mut local_var_req_builder = local_var_client.request(reqwest::Method::POST, local_var_uri_str.as_str());

    if let Some(ref local_var_user_agent) = local_var_configuration.user_agent {
        local_var_req_builder = local_var_req_builder.header(reqwest::header::USER_AGENT, local_var_user_agent.clone());
    }
    if let Some(ref local_var_token) = local_var_configuration.oauth_access_token {
        local_var_req_builder = local_var_req_builder.bearer_auth(local_var_token.to_owned());
    };
    local_var_req_builder = local_var_req_builder.json(&post_shield_information_barriers_change_status_request);

    let local_var_req = local_var_req_builder.build()?;
    let local_var_resp = local_var_client.execute(local_var_req).await?;

    let local_var_status = local_var_resp.status();
    let local_var_content = local_var_resp.text().await?;

    if !local_var_status.is_client_error() && !local_var_status.is_server_error() {
        serde_json::from_str(&local_var_content).map_err(Error::from)
    } else {
        let local_var_entity: Option<PostShieldInformationBarriersChangeStatusError> = serde_json::from_str(&local_var_content).ok();
        let local_var_error = ResponseContent { status: local_var_status, content: local_var_content, entity: local_var_entity };
        Err(Error::ResponseError(local_var_error))
    }
}

