/*
 * Box Platform API
 *
 * [Box Platform](https://box.dev) provides functionality to provide access to content stored within [Box](https://box.com). It provides endpoints for basic manipulation of files and folders, management of users within an enterprise, as well as more complex topics such as legal holds and retention policies.
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: devrel@box.com
 * Generated by: https://openapi-generator.tech
 */


use reqwest;

use crate::apis::ResponseContent;
use super::{Error, configuration};

/// struct for passing parameters to the method [`get_terms_of_services`]
#[derive(Clone, Debug, Default)]
pub struct GetTermsOfServicesParams {
    /// Limits the results to the terms of service of the given type.
    pub tos_type: Option<String>
}

/// struct for passing parameters to the method [`get_terms_of_services_id`]
#[derive(Clone, Debug, Default)]
pub struct GetTermsOfServicesIdParams {
    /// The ID of the terms of service.
    pub terms_of_service_id: String
}

/// struct for passing parameters to the method [`post_terms_of_services`]
#[derive(Clone, Debug, Default)]
pub struct PostTermsOfServicesParams {
    pub post_terms_of_services_request: Option<crate::models::PostTermsOfServicesRequest>
}

/// struct for passing parameters to the method [`put_terms_of_services_id`]
#[derive(Clone, Debug, Default)]
pub struct PutTermsOfServicesIdParams {
    /// The ID of the terms of service.
    pub terms_of_service_id: String,
    pub put_terms_of_services_id_request: Option<crate::models::PutTermsOfServicesIdRequest>
}


/// struct for typed errors of method [`get_terms_of_services`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum GetTermsOfServicesError {
    DefaultResponse(crate::models::ClientError),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`get_terms_of_services_id`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum GetTermsOfServicesIdError {
    DefaultResponse(crate::models::ClientError),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`post_terms_of_services`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum PostTermsOfServicesError {
    DefaultResponse(crate::models::ClientError),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`put_terms_of_services_id`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum PutTermsOfServicesIdError {
    DefaultResponse(crate::models::ClientError),
    UnknownValue(serde_json::Value),
}


/// Returns the current terms of service text and settings for the enterprise.
pub async fn get_terms_of_services(configuration: &configuration::Configuration, params: GetTermsOfServicesParams) -> Result<crate::models::TermsOfServices, Error<GetTermsOfServicesError>> {
    let local_var_configuration = configuration;

    // unbox the parameters
    let tos_type = params.tos_type;


    let local_var_client = &local_var_configuration.client;

    let local_var_uri_str = format!("{}/terms_of_services", local_var_configuration.base_path);
    let mut local_var_req_builder = local_var_client.request(reqwest::Method::GET, local_var_uri_str.as_str());

    if let Some(ref local_var_str) = tos_type {
        local_var_req_builder = local_var_req_builder.query(&[("tos_type", &local_var_str.to_string())]);
    }
    if let Some(ref local_var_user_agent) = local_var_configuration.user_agent {
        local_var_req_builder = local_var_req_builder.header(reqwest::header::USER_AGENT, local_var_user_agent.clone());
    }
    if let Some(ref local_var_token) = local_var_configuration.oauth_access_token {
        local_var_req_builder = local_var_req_builder.bearer_auth(local_var_token.to_owned());
    };

    let local_var_req = local_var_req_builder.build()?;
    let local_var_resp = local_var_client.execute(local_var_req).await?;

    let local_var_status = local_var_resp.status();
    let local_var_content = local_var_resp.text().await?;

    if !local_var_status.is_client_error() && !local_var_status.is_server_error() {
        serde_json::from_str(&local_var_content).map_err(Error::from)
    } else {
        let local_var_entity: Option<GetTermsOfServicesError> = serde_json::from_str(&local_var_content).ok();
        let local_var_error = ResponseContent { status: local_var_status, content: local_var_content, entity: local_var_entity };
        Err(Error::ResponseError(local_var_error))
    }
}

/// Fetches a specific terms of service.
pub async fn get_terms_of_services_id(configuration: &configuration::Configuration, params: GetTermsOfServicesIdParams) -> Result<crate::models::TermsOfService, Error<GetTermsOfServicesIdError>> {
    let local_var_configuration = configuration;

    // unbox the parameters
    let terms_of_service_id = params.terms_of_service_id;


    let local_var_client = &local_var_configuration.client;

    let local_var_uri_str = format!("{}/terms_of_services/{terms_of_service_id}", local_var_configuration.base_path, terms_of_service_id=crate::apis::urlencode(terms_of_service_id));
    let mut local_var_req_builder = local_var_client.request(reqwest::Method::GET, local_var_uri_str.as_str());

    if let Some(ref local_var_user_agent) = local_var_configuration.user_agent {
        local_var_req_builder = local_var_req_builder.header(reqwest::header::USER_AGENT, local_var_user_agent.clone());
    }
    if let Some(ref local_var_token) = local_var_configuration.oauth_access_token {
        local_var_req_builder = local_var_req_builder.bearer_auth(local_var_token.to_owned());
    };

    let local_var_req = local_var_req_builder.build()?;
    let local_var_resp = local_var_client.execute(local_var_req).await?;

    let local_var_status = local_var_resp.status();
    let local_var_content = local_var_resp.text().await?;

    if !local_var_status.is_client_error() && !local_var_status.is_server_error() {
        serde_json::from_str(&local_var_content).map_err(Error::from)
    } else {
        let local_var_entity: Option<GetTermsOfServicesIdError> = serde_json::from_str(&local_var_content).ok();
        let local_var_error = ResponseContent { status: local_var_status, content: local_var_content, entity: local_var_entity };
        Err(Error::ResponseError(local_var_error))
    }
}

/// Creates a terms of service for a given enterprise and type of user.
pub async fn post_terms_of_services(configuration: &configuration::Configuration, params: PostTermsOfServicesParams) -> Result<crate::models::Task, Error<PostTermsOfServicesError>> {
    let local_var_configuration = configuration;

    // unbox the parameters
    let post_terms_of_services_request = params.post_terms_of_services_request;


    let local_var_client = &local_var_configuration.client;

    let local_var_uri_str = format!("{}/terms_of_services", local_var_configuration.base_path);
    let mut local_var_req_builder = local_var_client.request(reqwest::Method::POST, local_var_uri_str.as_str());

    if let Some(ref local_var_user_agent) = local_var_configuration.user_agent {
        local_var_req_builder = local_var_req_builder.header(reqwest::header::USER_AGENT, local_var_user_agent.clone());
    }
    if let Some(ref local_var_token) = local_var_configuration.oauth_access_token {
        local_var_req_builder = local_var_req_builder.bearer_auth(local_var_token.to_owned());
    };
    local_var_req_builder = local_var_req_builder.json(&post_terms_of_services_request);

    let local_var_req = local_var_req_builder.build()?;
    let local_var_resp = local_var_client.execute(local_var_req).await?;

    let local_var_status = local_var_resp.status();
    let local_var_content = local_var_resp.text().await?;

    if !local_var_status.is_client_error() && !local_var_status.is_server_error() {
        serde_json::from_str(&local_var_content).map_err(Error::from)
    } else {
        let local_var_entity: Option<PostTermsOfServicesError> = serde_json::from_str(&local_var_content).ok();
        let local_var_error = ResponseContent { status: local_var_status, content: local_var_content, entity: local_var_entity };
        Err(Error::ResponseError(local_var_error))
    }
}

/// Updates a specific terms of service.
pub async fn put_terms_of_services_id(configuration: &configuration::Configuration, params: PutTermsOfServicesIdParams) -> Result<crate::models::TermsOfService, Error<PutTermsOfServicesIdError>> {
    let local_var_configuration = configuration;

    // unbox the parameters
    let terms_of_service_id = params.terms_of_service_id;
    let put_terms_of_services_id_request = params.put_terms_of_services_id_request;


    let local_var_client = &local_var_configuration.client;

    let local_var_uri_str = format!("{}/terms_of_services/{terms_of_service_id}", local_var_configuration.base_path, terms_of_service_id=crate::apis::urlencode(terms_of_service_id));
    let mut local_var_req_builder = local_var_client.request(reqwest::Method::PUT, local_var_uri_str.as_str());

    if let Some(ref local_var_user_agent) = local_var_configuration.user_agent {
        local_var_req_builder = local_var_req_builder.header(reqwest::header::USER_AGENT, local_var_user_agent.clone());
    }
    if let Some(ref local_var_token) = local_var_configuration.oauth_access_token {
        local_var_req_builder = local_var_req_builder.bearer_auth(local_var_token.to_owned());
    };
    local_var_req_builder = local_var_req_builder.json(&put_terms_of_services_id_request);

    let local_var_req = local_var_req_builder.build()?;
    let local_var_resp = local_var_client.execute(local_var_req).await?;

    let local_var_status = local_var_resp.status();
    let local_var_content = local_var_resp.text().await?;

    if !local_var_status.is_client_error() && !local_var_status.is_server_error() {
        serde_json::from_str(&local_var_content).map_err(Error::from)
    } else {
        let local_var_entity: Option<PutTermsOfServicesIdError> = serde_json::from_str(&local_var_content).ok();
        let local_var_error = ResponseContent { status: local_var_status, content: local_var_content, entity: local_var_entity };
        Err(Error::ResponseError(local_var_error))
    }
}

