/*
 * Box Platform API
 *
 * [Box Platform](https://box.dev) provides functionality to provide access to content stored within [Box](https://box.com). It provides endpoints for basic manipulation of files and folders, management of users within an enterprise, as well as more complex topics such as legal holds and retention policies.
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: devrel@box.com
 * Generated by: https://openapi-generator.tech
 */


use reqwest;

use crate::apis::ResponseContent;
use super::{Error, configuration};

/// struct for passing parameters to the method [`get_terms_of_service_user_statuses`]
#[derive(Clone, Debug, Default)]
pub struct GetTermsOfServiceUserStatusesParams {
    /// The ID of the terms of service.
    pub tos_id: String,
    /// Limits results to the given user ID.
    pub user_id: Option<String>
}

/// struct for passing parameters to the method [`post_terms_of_service_user_statuses`]
#[derive(Clone, Debug, Default)]
pub struct PostTermsOfServiceUserStatusesParams {
    pub post_terms_of_service_user_statuses_request: Option<crate::models::PostTermsOfServiceUserStatusesRequest>
}

/// struct for passing parameters to the method [`put_terms_of_service_user_statuses_id`]
#[derive(Clone, Debug, Default)]
pub struct PutTermsOfServiceUserStatusesIdParams {
    /// The ID of the terms of service status.
    pub terms_of_service_user_status_id: String,
    pub put_terms_of_service_user_statuses_id_request: Option<crate::models::PutTermsOfServiceUserStatusesIdRequest>
}


/// struct for typed errors of method [`get_terms_of_service_user_statuses`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum GetTermsOfServiceUserStatusesError {
    DefaultResponse(crate::models::ClientError),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`post_terms_of_service_user_statuses`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum PostTermsOfServiceUserStatusesError {
    DefaultResponse(crate::models::ClientError),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`put_terms_of_service_user_statuses_id`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum PutTermsOfServiceUserStatusesIdError {
    DefaultResponse(crate::models::ClientError),
    UnknownValue(serde_json::Value),
}


/// Retrieves an overview of users and their status for a terms of service, including Whether they have accepted the terms and when.
pub async fn get_terms_of_service_user_statuses(configuration: &configuration::Configuration, params: GetTermsOfServiceUserStatusesParams) -> Result<crate::models::TermsOfServiceUserStatuses, Error<GetTermsOfServiceUserStatusesError>> {
    let local_var_configuration = configuration;

    // unbox the parameters
    let tos_id = params.tos_id;
    let user_id = params.user_id;


    let local_var_client = &local_var_configuration.client;

    let local_var_uri_str = format!("{}/terms_of_service_user_statuses", local_var_configuration.base_path);
    let mut local_var_req_builder = local_var_client.request(reqwest::Method::GET, local_var_uri_str.as_str());

    local_var_req_builder = local_var_req_builder.query(&[("tos_id", &tos_id.to_string())]);
    if let Some(ref local_var_str) = user_id {
        local_var_req_builder = local_var_req_builder.query(&[("user_id", &local_var_str.to_string())]);
    }
    if let Some(ref local_var_user_agent) = local_var_configuration.user_agent {
        local_var_req_builder = local_var_req_builder.header(reqwest::header::USER_AGENT, local_var_user_agent.clone());
    }
    if let Some(ref local_var_token) = local_var_configuration.oauth_access_token {
        local_var_req_builder = local_var_req_builder.bearer_auth(local_var_token.to_owned());
    };

    let local_var_req = local_var_req_builder.build()?;
    let local_var_resp = local_var_client.execute(local_var_req).await?;

    let local_var_status = local_var_resp.status();
    let local_var_content = local_var_resp.text().await?;

    if !local_var_status.is_client_error() && !local_var_status.is_server_error() {
        serde_json::from_str(&local_var_content).map_err(Error::from)
    } else {
        let local_var_entity: Option<GetTermsOfServiceUserStatusesError> = serde_json::from_str(&local_var_content).ok();
        let local_var_error = ResponseContent { status: local_var_status, content: local_var_content, entity: local_var_entity };
        Err(Error::ResponseError(local_var_error))
    }
}

/// Sets the status for a terms of service for a user.
pub async fn post_terms_of_service_user_statuses(configuration: &configuration::Configuration, params: PostTermsOfServiceUserStatusesParams) -> Result<crate::models::TermsOfServiceUserStatus, Error<PostTermsOfServiceUserStatusesError>> {
    let local_var_configuration = configuration;

    // unbox the parameters
    let post_terms_of_service_user_statuses_request = params.post_terms_of_service_user_statuses_request;


    let local_var_client = &local_var_configuration.client;

    let local_var_uri_str = format!("{}/terms_of_service_user_statuses", local_var_configuration.base_path);
    let mut local_var_req_builder = local_var_client.request(reqwest::Method::POST, local_var_uri_str.as_str());

    if let Some(ref local_var_user_agent) = local_var_configuration.user_agent {
        local_var_req_builder = local_var_req_builder.header(reqwest::header::USER_AGENT, local_var_user_agent.clone());
    }
    if let Some(ref local_var_token) = local_var_configuration.oauth_access_token {
        local_var_req_builder = local_var_req_builder.bearer_auth(local_var_token.to_owned());
    };
    local_var_req_builder = local_var_req_builder.json(&post_terms_of_service_user_statuses_request);

    let local_var_req = local_var_req_builder.build()?;
    let local_var_resp = local_var_client.execute(local_var_req).await?;

    let local_var_status = local_var_resp.status();
    let local_var_content = local_var_resp.text().await?;

    if !local_var_status.is_client_error() && !local_var_status.is_server_error() {
        serde_json::from_str(&local_var_content).map_err(Error::from)
    } else {
        let local_var_entity: Option<PostTermsOfServiceUserStatusesError> = serde_json::from_str(&local_var_content).ok();
        let local_var_error = ResponseContent { status: local_var_status, content: local_var_content, entity: local_var_entity };
        Err(Error::ResponseError(local_var_error))
    }
}

/// Updates the status for a terms of service for a user.
pub async fn put_terms_of_service_user_statuses_id(configuration: &configuration::Configuration, params: PutTermsOfServiceUserStatusesIdParams) -> Result<crate::models::TermsOfServiceUserStatus, Error<PutTermsOfServiceUserStatusesIdError>> {
    let local_var_configuration = configuration;

    // unbox the parameters
    let terms_of_service_user_status_id = params.terms_of_service_user_status_id;
    let put_terms_of_service_user_statuses_id_request = params.put_terms_of_service_user_statuses_id_request;


    let local_var_client = &local_var_configuration.client;

    let local_var_uri_str = format!("{}/terms_of_service_user_statuses/{terms_of_service_user_status_id}", local_var_configuration.base_path, terms_of_service_user_status_id=crate::apis::urlencode(terms_of_service_user_status_id));
    let mut local_var_req_builder = local_var_client.request(reqwest::Method::PUT, local_var_uri_str.as_str());

    if let Some(ref local_var_user_agent) = local_var_configuration.user_agent {
        local_var_req_builder = local_var_req_builder.header(reqwest::header::USER_AGENT, local_var_user_agent.clone());
    }
    if let Some(ref local_var_token) = local_var_configuration.oauth_access_token {
        local_var_req_builder = local_var_req_builder.bearer_auth(local_var_token.to_owned());
    };
    local_var_req_builder = local_var_req_builder.json(&put_terms_of_service_user_statuses_id_request);

    let local_var_req = local_var_req_builder.build()?;
    let local_var_resp = local_var_client.execute(local_var_req).await?;

    let local_var_status = local_var_resp.status();
    let local_var_content = local_var_resp.text().await?;

    if !local_var_status.is_client_error() && !local_var_status.is_server_error() {
        serde_json::from_str(&local_var_content).map_err(Error::from)
    } else {
        let local_var_entity: Option<PutTermsOfServiceUserStatusesIdError> = serde_json::from_str(&local_var_content).ok();
        let local_var_error = ResponseContent { status: local_var_status, content: local_var_content, entity: local_var_entity };
        Err(Error::ResponseError(local_var_error))
    }
}

