/*
 * Box Platform API
 *
 * [Box Platform](https://box.dev) provides functionality to provide access to content stored within [Box](https://box.com). It provides endpoints for basic manipulation of files and folders, management of users within an enterprise, as well as more complex topics such as legal holds and retention policies.
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: devrel@box.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct CollaborationAcceptanceRequirementsStatus {
    #[serde(rename = "terms_of_service_requirement", skip_serializing_if = "Option::is_none")]
    pub terms_of_service_requirement: Option<Box<crate::models::CollaborationAcceptanceRequirementsStatusTermsOfServiceRequirement>>,
    #[serde(rename = "strong_password_requirement", skip_serializing_if = "Option::is_none")]
    pub strong_password_requirement: Option<Box<crate::models::CollaborationAcceptanceRequirementsStatusStrongPasswordRequirement>>,
    #[serde(rename = "two_factor_authentication_requirement", skip_serializing_if = "Option::is_none")]
    pub two_factor_authentication_requirement: Option<Box<crate::models::CollaborationAcceptanceRequirementsStatusTwoFactorAuthenticationRequirement>>,
}

impl CollaborationAcceptanceRequirementsStatus {
    pub fn new() -> CollaborationAcceptanceRequirementsStatus {
        CollaborationAcceptanceRequirementsStatus {
            terms_of_service_requirement: None,
            strong_password_requirement: None,
            two_factor_authentication_requirement: None,
        }
    }
}


