/*
 * Box Platform API
 *
 * [Box Platform](https://box.dev) provides functionality to provide access to content stored within [Box](https://box.com). It provides endpoints for basic manipulation of files and folders, management of users within an enterprise, as well as more complex topics such as legal holds and retention policies.
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: devrel@box.com
 * Generated by: https://openapi-generator.tech
 */

/// EventSourceClassification : The object containing classification information for the item that triggered the event. This field will not appear if the item does not have a classification set.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct EventSourceClassification {
    /// The classification's name
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
}

impl EventSourceClassification {
    /// The object containing classification information for the item that triggered the event. This field will not appear if the item does not have a classification set.
    pub fn new() -> EventSourceClassification {
        EventSourceClassification {
            name: None,
        }
    }
}


