/*
 * Box Platform API
 *
 * [Box Platform](https://box.dev) provides functionality to provide access to content stored within [Box](https://box.com). It provides endpoints for basic manipulation of files and folders, management of users within an enterprise, as well as more complex topics such as legal holds and retention policies.
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: devrel@box.com
 * Generated by: https://openapi-generator.tech
 */

/// FileRequestUpdateRequest : The request body to update a file request.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct FileRequestUpdateRequest {
    /// An optional new title for the file request. This can be used to change the title of the file request.  This will default to the value on the existing file request.
    #[serde(rename = "title", skip_serializing_if = "Option::is_none")]
    pub title: Option<String>,
    /// An optional new description for the file request. This can be used to change the description of the file request.  This will default to the value on the existing file request.
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    /// An optional new status of the file request.  When the status is set to `inactive`, the file request will no longer accept new submissions, and any visitor to the file request URL will receive a `HTTP 404` status code.  This will default to the value on the existing file request.
    #[serde(rename = "status", skip_serializing_if = "Option::is_none")]
    pub status: Option<Status>,
    /// Whether a file request submitter is required to provide their email address.  When this setting is set to true, the Box UI will show an email field on the file request form.  This will default to the value on the existing file request.
    #[serde(rename = "is_email_required", skip_serializing_if = "Option::is_none")]
    pub is_email_required: Option<bool>,
    /// Whether a file request submitter is required to provide a description of the files they are submitting.  When this setting is set to true, the Box UI will show a description field on the file request form.  This will default to the value on the existing file request.
    #[serde(rename = "is_description_required", skip_serializing_if = "Option::is_none")]
    pub is_description_required: Option<bool>,
    /// The date after which a file request will no longer accept new submissions.  After this date, the `status` will automatically be set to `inactive`.  This will default to the value on the existing file request.
    #[serde(rename = "expires_at", skip_serializing_if = "Option::is_none")]
    pub expires_at: Option<String>,
}

impl FileRequestUpdateRequest {
    /// The request body to update a file request.
    pub fn new() -> FileRequestUpdateRequest {
        FileRequestUpdateRequest {
            title: None,
            description: None,
            status: None,
            is_email_required: None,
            is_description_required: None,
            expires_at: None,
        }
    }
}

/// An optional new status of the file request.  When the status is set to `inactive`, the file request will no longer accept new submissions, and any visitor to the file request URL will receive a `HTTP 404` status code.  This will default to the value on the existing file request.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Status {
    #[serde(rename = "active")]
    Active,
    #[serde(rename = "inactive")]
    Inactive,
}

impl Default for Status {
    fn default() -> Status {
        Self::Active
    }
}

