/*
 * Box Platform API
 *
 * [Box Platform](https://box.dev) provides functionality to provide access to content stored within [Box](https://box.com). It provides endpoints for basic manipulation of files and folders, management of users within an enterprise, as well as more complex topics such as legal holds and retention policies.
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: devrel@box.com
 * Generated by: https://openapi-generator.tech
 */

/// FileVersionMini : A mini representation of a file version, used when nested within another resource.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct FileVersionMini {
    /// The unique identifier that represent a file version.
    #[serde(rename = "id")]
    pub id: String,
    /// `file_version`
    #[serde(rename = "type")]
    pub r#type: RHashType,
    /// The SHA1 hash of this version of the file.
    #[serde(rename = "sha1", skip_serializing_if = "Option::is_none")]
    pub sha1: Option<String>,
}

impl FileVersionMini {
    /// A mini representation of a file version, used when nested within another resource.
    pub fn new(id: String, r#type: RHashType) -> FileVersionMini {
        FileVersionMini {
            id,
            r#type,
            sha1: None,
        }
    }
}

/// `file_version`
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum RHashType {
    #[serde(rename = "file_version")]
    FileVersion,
}

impl Default for RHashType {
    fn default() -> RHashType {
        Self::FileVersion
    }
}

