/*
 * Box Platform API
 *
 * [Box Platform](https://box.dev) provides functionality to provide access to content stored within [Box](https://box.com). It provides endpoints for basic manipulation of files and folders, management of users within an enterprise, as well as more complex topics such as legal holds and retention policies.
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: devrel@box.com
 * Generated by: https://openapi-generator.tech
 */

/// FileRequest : A standard representation of a file request, as returned from any file request API endpoints by default.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct FileRequest {
    /// The unique identifier for this file request.
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    /// `file_request`
    #[serde(rename = "type", skip_serializing_if = "Option::is_none")]
    pub r#type: Option<RHashType>,
    /// The title of file request. This is shown in the Box UI to users uploading files.  This defaults to title of the file request that was copied to create this file request.
    #[serde(rename = "title", skip_serializing_if = "Option::is_none")]
    pub title: Option<String>,
    /// The optional description of this file request. This is shown in the Box UI to users uploading files.  This defaults to description of the file request that was copied to create this file request.
    #[serde(rename = "description", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub description: Option<Option<String>>,
    /// The status of the file request. This defaults to `active`.  When the status is set to `inactive`, the file request will no longer accept new submissions, and any visitor to the file request URL will receive a `HTTP 404` status code.  This defaults to status of file request that was copied to create this file request.
    #[serde(rename = "status", skip_serializing_if = "Option::is_none")]
    pub status: Option<Status>,
    /// Whether a file request submitter is required to provide their email address.  When this setting is set to true, the Box UI will show an email field on the file request form.  This defaults to setting of file request that was copied to create this file request.
    #[serde(rename = "is_email_required", skip_serializing_if = "Option::is_none")]
    pub is_email_required: Option<bool>,
    /// Whether a file request submitter is required to provide a description of the files they are submitting.  When this setting is set to true, the Box UI will show a description field on the file request form.  This defaults to setting of file request that was copied to create this file request.
    #[serde(rename = "is_description_required", skip_serializing_if = "Option::is_none")]
    pub is_description_required: Option<bool>,
    /// The date after which a file request will no longer accept new submissions.  After this date, the `status` will automatically be set to `inactive`.
    #[serde(rename = "expires_at", skip_serializing_if = "Option::is_none")]
    pub expires_at: Option<String>,
    #[serde(rename = "folder")]
    pub folder: Box<crate::models::FileRequestFolder>,
    /// The generated URL for this file request. This URL can be shared with users to let them upload files to the associated folder.
    #[serde(rename = "url", skip_serializing_if = "Option::is_none")]
    pub url: Option<String>,
    /// The HTTP `etag` of this file. This can be used in combination with the `If-Match` header when updating a file request. By providing that header, a change will only be performed on the  file request if the `etag` on the file request still matches the `etag` provided in the `If-Match` header.
    #[serde(rename = "etag", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub etag: Option<Option<String>>,
    #[serde(rename = "created_by", skip_serializing_if = "Option::is_none")]
    pub created_by: Option<Box<crate::models::FileRequestCreatedBy>>,
    /// The date and time when the file request was created.
    #[serde(rename = "created_at")]
    pub created_at: String,
    #[serde(rename = "updated_by", skip_serializing_if = "Option::is_none")]
    pub updated_by: Option<Box<crate::models::FileRequestUpdatedBy>>,
    /// The date and time when the file request was last updated.
    #[serde(rename = "updated_at")]
    pub updated_at: String,
}

impl FileRequest {
    /// A standard representation of a file request, as returned from any file request API endpoints by default.
    pub fn new(folder: crate::models::FileRequestFolder, created_at: String, updated_at: String) -> FileRequest {
        FileRequest {
            id: None,
            r#type: None,
            title: None,
            description: None,
            status: None,
            is_email_required: None,
            is_description_required: None,
            expires_at: None,
            folder: Box::new(folder),
            url: None,
            etag: None,
            created_by: None,
            created_at,
            updated_by: None,
            updated_at,
        }
    }
}

/// `file_request`
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum RHashType {
    #[serde(rename = "file_request")]
    FileRequest,
}

impl Default for RHashType {
    fn default() -> RHashType {
        Self::FileRequest
    }
}
/// The status of the file request. This defaults to `active`.  When the status is set to `inactive`, the file request will no longer accept new submissions, and any visitor to the file request URL will receive a `HTTP 404` status code.  This defaults to status of file request that was copied to create this file request.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Status {
    #[serde(rename = "active")]
    Active,
    #[serde(rename = "inactive")]
    Inactive,
}

impl Default for Status {
    fn default() -> Status {
        Self::Active
    }
}

