/*
 * Box Platform API
 *
 * [Box Platform](https://box.dev) provides functionality to provide access to content stored within [Box](https://box.com). It provides endpoints for basic manipulation of files and folders, management of users within an enterprise, as well as more complex topics such as legal holds and retention policies.
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: devrel@box.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct FolderFullAllOfPermissions {
    /// Specifies if the current user can delete this item.
    #[serde(rename = "can_delete")]
    pub can_delete: bool,
    /// Specifies if the current user can download this item.
    #[serde(rename = "can_download")]
    pub can_download: bool,
    /// Specifies if the current user can invite new users to collaborate on this item, and if the user can update the role of a user already collaborated on this item.
    #[serde(rename = "can_invite_collaborator")]
    pub can_invite_collaborator: bool,
    /// Specifies if the user can rename this item.
    #[serde(rename = "can_rename")]
    pub can_rename: bool,
    /// Specifies if the user can change the access level of an existing shared link on this item.
    #[serde(rename = "can_set_share_access")]
    pub can_set_share_access: bool,
    /// Specifies if the user can create a shared link for this item.
    #[serde(rename = "can_share")]
    pub can_share: bool,
    /// Specifies if the user can upload into this folder.
    #[serde(rename = "can_upload")]
    pub can_upload: bool,
}

impl FolderFullAllOfPermissions {
    pub fn new(can_delete: bool, can_download: bool, can_invite_collaborator: bool, can_rename: bool, can_set_share_access: bool, can_share: bool, can_upload: bool) -> FolderFullAllOfPermissions {
        FolderFullAllOfPermissions {
            can_delete,
            can_download,
            can_invite_collaborator,
            can_rename,
            can_set_share_access,
            can_share,
            can_upload,
        }
    }
}


