/*
 * Box Platform API
 *
 * [Box Platform](https://box.dev) provides functionality to provide access to content stored within [Box](https://box.com). It provides endpoints for basic manipulation of files and folders, management of users within an enterprise, as well as more complex topics such as legal holds and retention policies.
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: devrel@box.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct PostShieldInformationBarrierSegmentMembersRequest {
    /// -| A type of the shield barrier segment member.
    #[serde(rename = "type", skip_serializing_if = "Option::is_none")]
    pub r#type: Option<RHashType>,
    #[serde(rename = "shield_information_barrier", skip_serializing_if = "Option::is_none")]
    pub shield_information_barrier: Option<Box<crate::models::ShieldInformationBarrierBase>>,
    #[serde(rename = "shield_information_barrier_segment")]
    pub shield_information_barrier_segment: Box<crate::models::PostShieldInformationBarrierSegmentMembersRequestShieldInformationBarrierSegment>,
    #[serde(rename = "user")]
    pub user: Box<crate::models::PostShieldInformationBarrierSegmentMembersRequestUser>,
}

impl PostShieldInformationBarrierSegmentMembersRequest {
    pub fn new(shield_information_barrier_segment: crate::models::PostShieldInformationBarrierSegmentMembersRequestShieldInformationBarrierSegment, user: crate::models::PostShieldInformationBarrierSegmentMembersRequestUser) -> PostShieldInformationBarrierSegmentMembersRequest {
        PostShieldInformationBarrierSegmentMembersRequest {
            r#type: None,
            shield_information_barrier: None,
            shield_information_barrier_segment: Box::new(shield_information_barrier_segment),
            user: Box::new(user),
        }
    }
}

/// -| A type of the shield barrier segment member.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum RHashType {
    #[serde(rename = "shield_information_barrier_segment_member")]
    ShieldInformationBarrierSegmentMember,
}

impl Default for RHashType {
    fn default() -> RHashType {
        Self::ShieldInformationBarrierSegmentMember
    }
}

