/*
 * Box Platform API
 *
 * [Box Platform](https://box.dev) provides functionality to provide access to content stored within [Box](https://box.com). It provides endpoints for basic manipulation of files and folders, management of users within an enterprise, as well as more complex topics such as legal holds and retention policies.
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: devrel@box.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct PostTermsOfServicesRequest {
    /// Whether this terms of service is active.
    #[serde(rename = "status")]
    pub status: Status,
    /// The type of user to set the terms of service for.
    #[serde(rename = "tos_type", skip_serializing_if = "Option::is_none")]
    pub tos_type: Option<TosType>,
    /// The terms of service text to display to users.  The text can be set to empty if the `status` is set to `disabled`.
    #[serde(rename = "text")]
    pub text: String,
}

impl PostTermsOfServicesRequest {
    pub fn new(status: Status, text: String) -> PostTermsOfServicesRequest {
        PostTermsOfServicesRequest {
            status,
            tos_type: None,
            text,
        }
    }
}

/// Whether this terms of service is active.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Status {
    #[serde(rename = "enabled")]
    Enabled,
    #[serde(rename = "disabled")]
    Disabled,
}

impl Default for Status {
    fn default() -> Status {
        Self::Enabled
    }
}
/// The type of user to set the terms of service for.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum TosType {
    #[serde(rename = "external")]
    External,
    #[serde(rename = "managed")]
    Managed,
}

impl Default for TosType {
    fn default() -> TosType {
        Self::External
    }
}

