/*
 * Box Platform API
 *
 * [Box Platform](https://box.dev) provides functionality to provide access to content stored within [Box](https://box.com). It provides endpoints for basic manipulation of files and folders, management of users within an enterprise, as well as more complex topics such as legal holds and retention policies.
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: devrel@box.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct PostStoragePolicyAssignmentsRequest {
    #[serde(rename = "storage_policy")]
    pub storage_policy: Box<crate::models::PostStoragePolicyAssignmentsRequestStoragePolicy>,
    #[serde(rename = "assigned_to")]
    pub assigned_to: Box<crate::models::PostStoragePolicyAssignmentsRequestAssignedTo>,
}

impl PostStoragePolicyAssignmentsRequest {
    pub fn new(storage_policy: crate::models::PostStoragePolicyAssignmentsRequestStoragePolicy, assigned_to: crate::models::PostStoragePolicyAssignmentsRequestAssignedTo) -> PostStoragePolicyAssignmentsRequest {
        PostStoragePolicyAssignmentsRequest {
            storage_policy: Box::new(storage_policy),
            assigned_to: Box::new(assigned_to),
        }
    }
}


