/*
 * Box Platform API
 *
 * [Box Platform](https://box.dev) provides functionality to provide access to content stored within [Box](https://box.com). It provides endpoints for basic manipulation of files and folders, management of users within an enterprise, as well as more complex topics such as legal holds and retention policies.
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: devrel@box.com
 * Generated by: https://openapi-generator.tech
 */

/// PostWebLinksRequestParent : The parent folder to create the web link within.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct PostWebLinksRequestParent {
    /// The ID of parent folder
    #[serde(rename = "id")]
    pub id: String,
}

impl PostWebLinksRequestParent {
    /// The parent folder to create the web link within.
    pub fn new(id: String) -> PostWebLinksRequestParent {
        PostWebLinksRequestParent {
            id,
        }
    }
}


