/*
 * Box Platform API
 *
 * [Box Platform](https://box.dev) provides functionality to provide access to content stored within [Box](https://box.com). It provides endpoints for basic manipulation of files and folders, management of users within an enterprise, as well as more complex topics such as legal holds and retention policies.
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: devrel@box.com
 * Generated by: https://openapi-generator.tech
 */

/// PostCollaborationWhitelistExemptTargetsRequestUser : The user to exempt.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct PostCollaborationWhitelistExemptTargetsRequestUser {
    /// The ID of the user to exempt.
    #[serde(rename = "id")]
    pub id: String,
}

impl PostCollaborationWhitelistExemptTargetsRequestUser {
    /// The user to exempt.
    pub fn new(id: String) -> PostCollaborationWhitelistExemptTargetsRequestUser {
        PostCollaborationWhitelistExemptTargetsRequestUser {
            id,
        }
    }
}


