/*
 * Box Platform API
 *
 * [Box Platform](https://box.dev) provides functionality to provide access to content stored within [Box](https://box.com). It provides endpoints for basic manipulation of files and folders, management of users within an enterprise, as well as more complex topics such as legal holds and retention policies.
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: devrel@box.com
 * Generated by: https://openapi-generator.tech
 */

/// PostCollaborationsRequestItem : The item to attach the comment to.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct PostCollaborationsRequestItem {
    /// The type of the item that this collaboration will be granted access to
    #[serde(rename = "type")]
    pub r#type: RHashType,
    /// The ID of the item that will be granted access to
    #[serde(rename = "id")]
    pub id: String,
}

impl PostCollaborationsRequestItem {
    /// The item to attach the comment to.
    pub fn new(r#type: RHashType, id: String) -> PostCollaborationsRequestItem {
        PostCollaborationsRequestItem {
            r#type,
            id,
        }
    }
}

/// The type of the item that this collaboration will be granted access to
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum RHashType {
    #[serde(rename = "file")]
    File,
    #[serde(rename = "folder")]
    Folder,
}

impl Default for RHashType {
    fn default() -> RHashType {
        Self::File
    }
}

