/*
 * Box Platform API
 *
 * [Box Platform](https://box.dev) provides functionality to provide access to content stored within [Box](https://box.com). It provides endpoints for basic manipulation of files and folders, management of users within an enterprise, as well as more complex topics such as legal holds and retention policies.
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: devrel@box.com
 * Generated by: https://openapi-generator.tech
 */

/// PostLegalHoldPolicyAssignmentsRequestAssignTo : The item to assign the policy to



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct PostLegalHoldPolicyAssignmentsRequestAssignTo {
    /// The type of item to assign the policy to
    #[serde(rename = "type")]
    pub r#type: RHashType,
    /// The ID of item to assign the policy to
    #[serde(rename = "id")]
    pub id: String,
}

impl PostLegalHoldPolicyAssignmentsRequestAssignTo {
    /// The item to assign the policy to
    pub fn new(r#type: RHashType, id: String) -> PostLegalHoldPolicyAssignmentsRequestAssignTo {
        PostLegalHoldPolicyAssignmentsRequestAssignTo {
            r#type,
            id,
        }
    }
}

/// The type of item to assign the policy to
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum RHashType {
    #[serde(rename = "file")]
    File,
    #[serde(rename = "file_version")]
    FileVersion,
    #[serde(rename = "folder")]
    Folder,
    #[serde(rename = "user")]
    User,
}

impl Default for RHashType {
    fn default() -> RHashType {
        Self::File
    }
}

