/*
 * Box Platform API
 *
 * [Box Platform](https://box.dev) provides functionality to provide access to content stored within [Box](https://box.com). It provides endpoints for basic manipulation of files and folders, management of users within an enterprise, as well as more complex topics such as legal holds and retention policies.
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: devrel@box.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct PostTaskAssignmentsRequest {
    #[serde(rename = "task")]
    pub task: Box<crate::models::PostTaskAssignmentsRequestTask>,
    #[serde(rename = "assign_to")]
    pub assign_to: Box<crate::models::PostTaskAssignmentsRequestAssignTo>,
}

impl PostTaskAssignmentsRequest {
    pub fn new(task: crate::models::PostTaskAssignmentsRequestTask, assign_to: crate::models::PostTaskAssignmentsRequestAssignTo) -> PostTaskAssignmentsRequest {
        PostTaskAssignmentsRequest {
            task: Box::new(task),
            assign_to: Box::new(assign_to),
        }
    }
}


