/*
 * Box Platform API
 *
 * [Box Platform](https://box.dev) provides functionality to provide access to content stored within [Box](https://box.com). It provides endpoints for basic manipulation of files and folders, management of users within an enterprise, as well as more complex topics such as legal holds and retention policies.
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: devrel@box.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct PostLegalHoldPolicyAssignmentsRequest {
    /// The ID of the policy to assign.
    #[serde(rename = "policy_id")]
    pub policy_id: String,
    #[serde(rename = "assign_to")]
    pub assign_to: Box<crate::models::PostLegalHoldPolicyAssignmentsRequestAssignTo>,
}

impl PostLegalHoldPolicyAssignmentsRequest {
    pub fn new(policy_id: String, assign_to: crate::models::PostLegalHoldPolicyAssignmentsRequestAssignTo) -> PostLegalHoldPolicyAssignmentsRequest {
        PostLegalHoldPolicyAssignmentsRequest {
            policy_id,
            assign_to: Box::new(assign_to),
        }
    }
}


