/*
 * Box Platform API
 *
 * [Box Platform](https://box.dev) provides functionality to provide access to content stored within [Box](https://box.com). It provides endpoints for basic manipulation of files and folders, management of users within an enterprise, as well as more complex topics such as legal holds and retention policies.
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: devrel@box.com
 * Generated by: https://openapi-generator.tech
 */

/// PostCommentsRequestItem : The item to attach the comment to.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct PostCommentsRequestItem {
    /// The ID of the item
    #[serde(rename = "id")]
    pub id: String,
    /// The type of the item that this comment will be placed on.
    #[serde(rename = "type")]
    pub r#type: RHashType,
}

impl PostCommentsRequestItem {
    /// The item to attach the comment to.
    pub fn new(id: String, r#type: RHashType) -> PostCommentsRequestItem {
        PostCommentsRequestItem {
            id,
            r#type,
        }
    }
}

/// The type of the item that this comment will be placed on.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum RHashType {
    #[serde(rename = "file")]
    File,
    #[serde(rename = "comment")]
    Comment,
}

impl Default for RHashType {
    fn default() -> RHashType {
        Self::File
    }
}

