/*
 * Box Platform API
 *
 * [Box Platform](https://box.dev) provides functionality to provide access to content stored within [Box](https://box.com). It provides endpoints for basic manipulation of files and folders, management of users within an enterprise, as well as more complex topics such as legal holds and retention policies.
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: devrel@box.com
 * Generated by: https://openapi-generator.tech
 */

/// PostTasksRequestItem : The file to attach the task to.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct PostTasksRequestItem {
    /// The ID of the file
    #[serde(rename = "id")]
    pub id: String,
    /// `file`
    #[serde(rename = "type")]
    pub r#type: RHashType,
}

impl PostTasksRequestItem {
    /// The file to attach the task to.
    pub fn new(id: String, r#type: RHashType) -> PostTasksRequestItem {
        PostTasksRequestItem {
            id,
            r#type,
        }
    }
}

/// `file`
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum RHashType {
    #[serde(rename = "file")]
    File,
}

impl Default for RHashType {
    fn default() -> RHashType {
        Self::File
    }
}

