/*
 * Box Platform API
 *
 * [Box Platform](https://box.dev) provides functionality to provide access to content stored within [Box](https://box.com). It provides endpoints for basic manipulation of files and folders, management of users within an enterprise, as well as more complex topics such as legal holds and retention policies.
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: devrel@box.com
 * Generated by: https://openapi-generator.tech
 */

/// PutFilesIdMetadataGlobalBoxSkillsCardsRequestInner : An operation that replaces an existing card.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct PutFilesIdMetadataGlobalBoxSkillsCardsRequestInner {
    /// `replace`
    #[serde(rename = "op", skip_serializing_if = "Option::is_none")]
    pub op: Option<Op>,
    /// The JSON Path that represents the card to replace. In most cases this will be in the format `/cards/{index}` where `index` is the zero-indexed position of the card in the list of cards.
    #[serde(rename = "path", skip_serializing_if = "Option::is_none")]
    pub path: Option<String>,
    #[serde(rename = "value", skip_serializing_if = "Option::is_none")]
    pub value: Option<Box<crate::models::PutFilesIdMetadataGlobalBoxSkillsCardsRequestInnerValue>>,
}

impl PutFilesIdMetadataGlobalBoxSkillsCardsRequestInner {
    /// An operation that replaces an existing card.
    pub fn new() -> PutFilesIdMetadataGlobalBoxSkillsCardsRequestInner {
        PutFilesIdMetadataGlobalBoxSkillsCardsRequestInner {
            op: None,
            path: None,
            value: None,
        }
    }
}

/// `replace`
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Op {
    #[serde(rename = "replace")]
    Replace,
}

impl Default for Op {
    fn default() -> Op {
        Self::Replace
    }
}

