/*
 * Box Platform API
 *
 * [Box Platform](https://box.dev) provides functionality to provide access to content stored within [Box](https://box.com). It provides endpoints for basic manipulation of files and folders, management of users within an enterprise, as well as more complex topics such as legal holds and retention policies.
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: devrel@box.com
 * Generated by: https://openapi-generator.tech
 */

/// PutMetadataTemplatesEnterpriseSecurityClassification6VmVochwUwoSchemaUpdateRequestInner : A single classification to update.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct PutMetadataTemplatesEnterpriseSecurityClassification6VmVochwUwoSchemaUpdateRequestInner {
    /// `editEnumOption`
    #[serde(rename = "op")]
    pub op: String,
    /// `Box__Security__Classification__Key`
    #[serde(rename = "fieldKey")]
    pub field_key: String,
    /// The original label of the classification to change.
    #[serde(rename = "enumOptionKey")]
    pub enum_option_key: String,
    #[serde(rename = "data")]
    pub data: Box<crate::models::PutMetadataTemplatesEnterpriseSecurityClassification6VmVochwUwoSchemaUpdateRequestInnerData>,
}

impl PutMetadataTemplatesEnterpriseSecurityClassification6VmVochwUwoSchemaUpdateRequestInner {
    /// A single classification to update.
    pub fn new(op: String, field_key: String, enum_option_key: String, data: crate::models::PutMetadataTemplatesEnterpriseSecurityClassification6VmVochwUwoSchemaUpdateRequestInnerData) -> PutMetadataTemplatesEnterpriseSecurityClassification6VmVochwUwoSchemaUpdateRequestInner {
        PutMetadataTemplatesEnterpriseSecurityClassification6VmVochwUwoSchemaUpdateRequestInner {
            op,
            field_key,
            enum_option_key,
            data: Box::new(data),
        }
    }
}


