/*
 * Box Platform API
 *
 * [Box Platform](https://box.dev) provides functionality to provide access to content stored within [Box](https://box.com). It provides endpoints for basic manipulation of files and folders, management of users within an enterprise, as well as more complex topics such as legal holds and retention policies.
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: devrel@box.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct PutIntegrationMappingsSlackIdRequestBoxItem {
    /// Type of the mapped item referenced in `id`
    #[serde(rename = "type")]
    pub r#type: RHashType,
    /// ID of the mapped item (of type referenced in `type`)
    #[serde(rename = "id")]
    pub id: String,
}

impl PutIntegrationMappingsSlackIdRequestBoxItem {
    pub fn new(r#type: RHashType, id: String) -> PutIntegrationMappingsSlackIdRequestBoxItem {
        PutIntegrationMappingsSlackIdRequestBoxItem {
            r#type,
            id,
        }
    }
}

/// Type of the mapped item referenced in `id`
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum RHashType {
    #[serde(rename = "folder")]
    Folder,
}

impl Default for RHashType {
    fn default() -> RHashType {
        Self::Folder
    }
}

