/*
 * Box Platform API
 *
 * [Box Platform](https://box.dev) provides functionality to provide access to content stored within [Box](https://box.com). It provides endpoints for basic manipulation of files and folders, management of users within an enterprise, as well as more complex topics such as legal holds and retention policies.
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: devrel@box.com
 * Generated by: https://openapi-generator.tech
 */

/// PutMetadataTemplatesEnterpriseSecurityClassification6VmVochwUwoSchemaAddRequestInner : A single classification to add to the enterprise.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct PutMetadataTemplatesEnterpriseSecurityClassification6VmVochwUwoSchemaAddRequestInner {
    /// `addEnumOption`
    #[serde(rename = "op")]
    pub op: String,
    /// `Box__Security__Classification__Key`
    #[serde(rename = "fieldKey")]
    pub field_key: String,
    #[serde(rename = "data")]
    pub data: Box<crate::models::PutMetadataTemplatesEnterpriseSecurityClassification6VmVochwUwoSchemaAddRequestInnerData>,
}

impl PutMetadataTemplatesEnterpriseSecurityClassification6VmVochwUwoSchemaAddRequestInner {
    /// A single classification to add to the enterprise.
    pub fn new(op: String, field_key: String, data: crate::models::PutMetadataTemplatesEnterpriseSecurityClassification6VmVochwUwoSchemaAddRequestInnerData) -> PutMetadataTemplatesEnterpriseSecurityClassification6VmVochwUwoSchemaAddRequestInner {
        PutMetadataTemplatesEnterpriseSecurityClassification6VmVochwUwoSchemaAddRequestInner {
            op,
            field_key,
            data: Box::new(data),
        }
    }
}


