/*
 * Box Platform API
 *
 * [Box Platform](https://box.dev) provides functionality to provide access to content stored within [Box](https://box.com). It provides endpoints for basic manipulation of files and folders, management of users within an enterprise, as well as more complex topics such as legal holds and retention policies.
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: devrel@box.com
 * Generated by: https://openapi-generator.tech
 */

/// PutMetadataTemplatesEnterpriseSecurityClassification6VmVochwUwoSchemaUpdateRequestInnerData : The details of the updated classification.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct PutMetadataTemplatesEnterpriseSecurityClassification6VmVochwUwoSchemaUpdateRequestInnerData {
    /// A new label for the classification, as it will be shown in the web and mobile interfaces.
    #[serde(rename = "key")]
    pub key: String,
    #[serde(rename = "classification", skip_serializing_if = "Option::is_none")]
    pub classification: Option<Box<crate::models::PutMetadataTemplatesEnterpriseSecurityClassification6VmVochwUwoSchemaAddRequestInnerDataClassification>>,
}

impl PutMetadataTemplatesEnterpriseSecurityClassification6VmVochwUwoSchemaUpdateRequestInnerData {
    /// The details of the updated classification.
    pub fn new(key: String) -> PutMetadataTemplatesEnterpriseSecurityClassification6VmVochwUwoSchemaUpdateRequestInnerData {
        PutMetadataTemplatesEnterpriseSecurityClassification6VmVochwUwoSchemaUpdateRequestInnerData {
            key,
            classification: None,
        }
    }
}


