/*
 * Box Platform API
 *
 * [Box Platform](https://box.dev) provides functionality to provide access to content stored within [Box](https://box.com). It provides endpoints for basic manipulation of files and folders, management of users within an enterprise, as well as more complex topics such as legal holds and retention policies.
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: devrel@box.com
 * Generated by: https://openapi-generator.tech
 */

/// PutSkillInvocationsIdRequestUsage : A descriptor that defines what items are affected by this call.  Set this to the default values when setting a card to a `success` state, and leave it out in most other situations.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct PutSkillInvocationsIdRequestUsage {
    /// `file`
    #[serde(rename = "unit", skip_serializing_if = "Option::is_none")]
    pub unit: Option<String>,
    /// `1`
    #[serde(rename = "value", skip_serializing_if = "Option::is_none")]
    pub value: Option<f32>,
}

impl PutSkillInvocationsIdRequestUsage {
    /// A descriptor that defines what items are affected by this call.  Set this to the default values when setting a card to a `success` state, and leave it out in most other situations.
    pub fn new() -> PutSkillInvocationsIdRequestUsage {
        PutSkillInvocationsIdRequestUsage {
            unit: None,
            value: None,
        }
    }
}


