/*
 * Box Platform API
 *
 * [Box Platform](https://box.dev) provides functionality to provide access to content stored within [Box](https://box.com). It provides endpoints for basic manipulation of files and folders, management of users within an enterprise, as well as more complex topics such as legal holds and retention policies.
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: devrel@box.com
 * Generated by: https://openapi-generator.tech
 */

/// PutShieldInformationBarrierSegmentsIdRequest : An object containing update(s) to be made on the Shield Information Barrier Segment. Possible properties include 'name' and 'description', the value in object is the update.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct PutShieldInformationBarrierSegmentsIdRequest {
    /// The updated name for the shield information barrier segment.
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    /// The updated description for the shield information barrier segment.
    #[serde(rename = "description", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub description: Option<Option<String>>,
}

impl PutShieldInformationBarrierSegmentsIdRequest {
    /// An object containing update(s) to be made on the Shield Information Barrier Segment. Possible properties include 'name' and 'description', the value in object is the update.
    pub fn new() -> PutShieldInformationBarrierSegmentsIdRequest {
        PutShieldInformationBarrierSegmentsIdRequest {
            name: None,
            description: None,
        }
    }
}


