/*
 * Box Platform API
 *
 * [Box Platform](https://box.dev) provides functionality to provide access to content stored within [Box](https://box.com). It provides endpoints for basic manipulation of files and folders, management of users within an enterprise, as well as more complex topics such as legal holds and retention policies.
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: devrel@box.com
 * Generated by: https://openapi-generator.tech
 */

/// RepresentationsEntriesInnerProperties : An object containing the size and type of this presentation.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct RepresentationsEntriesInnerProperties {
    /// The width by height size of this representation in pixels.
    #[serde(rename = "dimensions", skip_serializing_if = "Option::is_none")]
    pub dimensions: Option<String>,
    /// Indicates if the representation is build up out of multiple pages.
    #[serde(rename = "paged", skip_serializing_if = "Option::is_none")]
    pub paged: Option<bool>,
    /// Indicates if the representation can be used as a thumbnail of the file.
    #[serde(rename = "thumb", skip_serializing_if = "Option::is_none")]
    pub thumb: Option<bool>,
}

impl RepresentationsEntriesInnerProperties {
    /// An object containing the size and type of this presentation.
    pub fn new() -> RepresentationsEntriesInnerProperties {
        RepresentationsEntriesInnerProperties {
            dimensions: None,
            paged: None,
            thumb: None,
        }
    }
}


