/*
 * Box Platform API
 *
 * [Box Platform](https://box.dev) provides functionality to provide access to content stored within [Box](https://box.com). It provides endpoints for basic manipulation of files and folders, management of users within an enterprise, as well as more complex topics such as legal holds and retention policies.
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: devrel@box.com
 * Generated by: https://openapi-generator.tech
 */

/// RetentionPolicyAssignmentAssignedTo : The `type` and `id` of the content that is under retention. The `type` can either be `folder` `enterprise`, or `metadata_template`.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct RetentionPolicyAssignmentAssignedTo {
    /// The ID of the folder, enterprise, or metadata template the policy is assigned to.
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    /// The type of resource the policy is assigned to.
    #[serde(rename = "type", skip_serializing_if = "Option::is_none")]
    pub r#type: Option<RHashType>,
}

impl RetentionPolicyAssignmentAssignedTo {
    /// The `type` and `id` of the content that is under retention. The `type` can either be `folder` `enterprise`, or `metadata_template`.
    pub fn new() -> RetentionPolicyAssignmentAssignedTo {
        RetentionPolicyAssignmentAssignedTo {
            id: None,
            r#type: None,
        }
    }
}

/// The type of resource the policy is assigned to.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum RHashType {
    #[serde(rename = "folder")]
    Folder,
    #[serde(rename = "enterprise")]
    Enterprise,
    #[serde(rename = "metadata_template")]
    MetadataTemplate,
}

impl Default for RHashType {
    fn default() -> RHashType {
        Self::Folder
    }
}

