/*
 * Box Platform API
 *
 * [Box Platform](https://box.dev) provides functionality to provide access to content stored within [Box](https://box.com). It provides endpoints for basic manipulation of files and folders, management of users within an enterprise, as well as more complex topics such as legal holds and retention policies.
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: devrel@box.com
 * Generated by: https://openapi-generator.tech
 */

/// RetentionPolicyAssignmentBase : A base representation of a retention policy assignment.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct RetentionPolicyAssignmentBase {
    /// The unique identifier that represents a file version.
    #[serde(rename = "id")]
    pub id: String,
    /// `retention_policy_assignment`
    #[serde(rename = "type")]
    pub r#type: RHashType,
}

impl RetentionPolicyAssignmentBase {
    /// A base representation of a retention policy assignment.
    pub fn new(id: String, r#type: RHashType) -> RetentionPolicyAssignmentBase {
        RetentionPolicyAssignmentBase {
            id,
            r#type,
        }
    }
}

/// `retention_policy_assignment`
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum RHashType {
    #[serde(rename = "retention_policy_assignment")]
    RetentionPolicyAssignment,
}

impl Default for RHashType {
    fn default() -> RHashType {
        Self::RetentionPolicyAssignment
    }
}

