/*
 * Box Platform API
 *
 * [Box Platform](https://box.dev) provides functionality to provide access to content stored within [Box](https://box.com). It provides endpoints for basic manipulation of files and folders, management of users within an enterprise, as well as more complex topics such as legal holds and retention policies.
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: devrel@box.com
 * Generated by: https://openapi-generator.tech
 */

/// ShieldInformationBarrierBase : A base representation of a shield information barrier object



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ShieldInformationBarrierBase {
    /// The unique identifier for the shield information barrier
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    /// The type of the shield information barrier
    #[serde(rename = "type", skip_serializing_if = "Option::is_none")]
    pub r#type: Option<RHashType>,
}

impl ShieldInformationBarrierBase {
    /// A base representation of a shield information barrier object
    pub fn new() -> ShieldInformationBarrierBase {
        ShieldInformationBarrierBase {
            id: None,
            r#type: None,
        }
    }
}

/// The type of the shield information barrier
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum RHashType {
    #[serde(rename = "shield_information_barrier")]
    ShieldInformationBarrier,
}

impl Default for RHashType {
    fn default() -> RHashType {
        Self::ShieldInformationBarrier
    }
}

