/*
 * Box Platform API
 *
 * [Box Platform](https://box.dev) provides functionality to provide access to content stored within [Box](https://box.com). It provides endpoints for basic manipulation of files and folders, management of users within an enterprise, as well as more complex topics such as legal holds and retention policies.
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: devrel@box.com
 * Generated by: https://openapi-generator.tech
 */

/// TimelineSkillCardEntriesInnerAppearsInner : The timestamp for an entry.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct TimelineSkillCardEntriesInnerAppearsInner {
    /// The time in seconds when an entry should start appearing on a timeline.
    #[serde(rename = "start", skip_serializing_if = "Option::is_none")]
    pub start: Option<i32>,
    /// The time in seconds when an entry should stop appearing on a timeline.
    #[serde(rename = "end", skip_serializing_if = "Option::is_none")]
    pub end: Option<i32>,
}

impl TimelineSkillCardEntriesInnerAppearsInner {
    /// The timestamp for an entry.
    pub fn new() -> TimelineSkillCardEntriesInnerAppearsInner {
        TimelineSkillCardEntriesInnerAppearsInner {
            start: None,
            end: None,
        }
    }
}


