/*
 * Box Platform API
 *
 * [Box Platform](https://box.dev) provides functionality to provide access to content stored within [Box](https://box.com). It provides endpoints for basic manipulation of files and folders, management of users within an enterprise, as well as more complex topics such as legal holds and retention policies.
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: devrel@box.com
 * Generated by: https://openapi-generator.tech
 */

/// TranscriptSkillCardEntriesInner : An entry in the `entries` attribute of a metadata card



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct TranscriptSkillCardEntriesInner {
    /// The text of the entry. This would be the transcribed text assigned to the entry on the timeline.
    #[serde(rename = "text", skip_serializing_if = "Option::is_none")]
    pub text: Option<String>,
    /// Defines when a transcribed bit of text appears. This only includes a start time and no end time.
    #[serde(rename = "appears", skip_serializing_if = "Option::is_none")]
    pub appears: Option<Vec<crate::models::TranscriptSkillCardEntriesInnerAppearsInner>>,
}

impl TranscriptSkillCardEntriesInner {
    /// An entry in the `entries` attribute of a metadata card
    pub fn new() -> TranscriptSkillCardEntriesInner {
        TranscriptSkillCardEntriesInner {
            text: None,
            appears: None,
        }
    }
}


