/*
 * Box Platform API
 *
 * [Box Platform](https://box.dev) provides functionality to provide access to content stored within [Box](https://box.com). It provides endpoints for basic manipulation of files and folders, management of users within an enterprise, as well as more complex topics such as legal holds and retention policies.
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: devrel@box.com
 * Generated by: https://openapi-generator.tech
 */

/// TrashFolderRestored : Represents a folder restored from the trash.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct TrashFolderRestored {
    /// The unique identifier that represent a folder.  The ID for any folder can be determined by visiting a folder in the web application and copying the ID from the URL. For example, for the URL `https://_*.app.box.com/folders/123` the `folder_id` is `123`.
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    /// The HTTP `etag` of this folder. This can be used within some API endpoints in the `If-Match` and `If-None-Match` headers to only perform changes on the folder if (no) changes have happened.
    #[serde(rename = "etag", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub etag: Option<Option<String>>,
    /// `folder`
    #[serde(rename = "type", skip_serializing_if = "Option::is_none")]
    pub r#type: Option<RHashType>,
    #[serde(rename = "sequence_id", skip_serializing_if = "Option::is_none")]
    pub sequence_id: Option<Box<String>>,
    /// The name of the folder.
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    /// The date and time when the folder was created. This value may be `null` for some folders such as the root folder or the trash folder.
    #[serde(rename = "created_at", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub created_at: Option<Option<String>>,
    /// The date and time when the folder was last updated. This value may be `null` for some folders such as the root folder or the trash folder.
    #[serde(rename = "modified_at", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub modified_at: Option<Option<String>>,
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<Box<String>>,
    /// The folder size in bytes.  Be careful parsing this integer as its value can get very large.
    #[serde(rename = "size", skip_serializing_if = "Option::is_none")]
    pub size: Option<i64>,
    #[serde(rename = "path_collection", skip_serializing_if = "Option::is_none")]
    pub path_collection: Option<Box<crate::models::FileAllOfPathCollection>>,
    #[serde(rename = "created_by", skip_serializing_if = "Option::is_none")]
    pub created_by: Option<Box<crate::models::FolderAllOfCreatedBy>>,
    #[serde(rename = "modified_by", skip_serializing_if = "Option::is_none")]
    pub modified_by: Option<Box<crate::models::FolderAllOfModifiedBy>>,
    /// The time at which this folder was put in the trash - becomes `null` after restore.
    #[serde(rename = "trashed_at", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub trashed_at: Option<Option<String>>,
    /// The time at which this folder is expected to be purged from the trash  - becomes `null` after restore.
    #[serde(rename = "purged_at", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub purged_at: Option<Option<String>>,
    /// The date and time at which this folder was originally created.
    #[serde(rename = "content_created_at", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub content_created_at: Option<Option<String>>,
    /// The date and time at which this folder was last updated.
    #[serde(rename = "content_modified_at", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub content_modified_at: Option<Option<String>>,
    #[serde(rename = "owned_by", skip_serializing_if = "Option::is_none")]
    pub owned_by: Option<Box<crate::models::FolderAllOfOwnedBy>>,
    /// The shared link for this file. This will be `null` if a folder had been trashed, even though the original shared link does become active again.
    #[serde(rename = "shared_link", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub shared_link: Option<Option<String>>,
    /// The folder upload email for this folder. This will be `null` if a folder has been trashed, even though the original upload email does become active again.
    #[serde(rename = "folder_upload_email", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub folder_upload_email: Option<Option<String>>,
    #[serde(rename = "parent", skip_serializing_if = "Option::is_none")]
    pub parent: Option<Box<crate::models::TrashFolderParent>>,
    /// Defines if this item has been deleted or not.  * `active` when the item has is not in the trash * `trashed` when the item has been moved to the trash but not deleted * `deleted` when the item has been permanently deleted.
    #[serde(rename = "item_status", skip_serializing_if = "Option::is_none")]
    pub item_status: Option<ItemStatus>,
}

impl TrashFolderRestored {
    /// Represents a folder restored from the trash.
    pub fn new() -> TrashFolderRestored {
        TrashFolderRestored {
            id: None,
            etag: None,
            r#type: None,
            sequence_id: None,
            name: None,
            created_at: None,
            modified_at: None,
            description: None,
            size: None,
            path_collection: None,
            created_by: None,
            modified_by: None,
            trashed_at: None,
            purged_at: None,
            content_created_at: None,
            content_modified_at: None,
            owned_by: None,
            shared_link: None,
            folder_upload_email: None,
            parent: None,
            item_status: None,
        }
    }
}

/// `folder`
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum RHashType {
    #[serde(rename = "folder")]
    Folder,
}

impl Default for RHashType {
    fn default() -> RHashType {
        Self::Folder
    }
}
/// Defines if this item has been deleted or not.  * `active` when the item has is not in the trash * `trashed` when the item has been moved to the trash but not deleted * `deleted` when the item has been permanently deleted.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum ItemStatus {
    #[serde(rename = "active")]
    Active,
    #[serde(rename = "trashed")]
    Trashed,
    #[serde(rename = "deleted")]
    Deleted,
}

impl Default for ItemStatus {
    fn default() -> ItemStatus {
        Self::Active
    }
}

