/*
 * Box Platform API
 *
 * [Box Platform](https://box.dev) provides functionality to provide access to content stored within [Box](https://box.com). It provides endpoints for basic manipulation of files and folders, management of users within an enterprise, as well as more complex topics such as legal holds and retention policies.
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: devrel@box.com
 * Generated by: https://openapi-generator.tech
 */

/// UploadedPart : A chunk of a file uploaded as part of an upload session, as returned by some endpoints.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct UploadedPart {
    #[serde(rename = "part", skip_serializing_if = "Option::is_none")]
    pub part: Option<Box<crate::models::UploadPart>>,
}

impl UploadedPart {
    /// A chunk of a file uploaded as part of an upload session, as returned by some endpoints.
    pub fn new() -> UploadedPart {
        UploadedPart {
            part: None,
        }
    }
}


