/*
 * Box Platform API
 *
 * [Box Platform](https://box.dev) provides functionality to provide access to content stored within [Box](https://box.com). It provides endpoints for basic manipulation of files and folders, management of users within an enterprise, as well as more complex topics such as legal holds and retention policies.
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: devrel@box.com
 * Generated by: https://openapi-generator.tech
 */

/// WebLinkBase : Web links are objects that point to URLs. These objects are also known as bookmarks within the Box web application.  Web link objects are treated similarly to file objects, they will also support most actions that apply to regular files.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct WebLinkBase {
    /// The unique identifier for this web link
    #[serde(rename = "id")]
    pub id: String,
    /// `web_link`
    #[serde(rename = "type")]
    pub r#type: RHashType,
    /// The entity tag of this web link. Used with `If-Match` headers.
    #[serde(rename = "etag", skip_serializing_if = "Option::is_none")]
    pub etag: Option<String>,
}

impl WebLinkBase {
    /// Web links are objects that point to URLs. These objects are also known as bookmarks within the Box web application.  Web link objects are treated similarly to file objects, they will also support most actions that apply to regular files.
    pub fn new(id: String, r#type: RHashType) -> WebLinkBase {
        WebLinkBase {
            id,
            r#type,
            etag: None,
        }
    }
}

/// `web_link`
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum RHashType {
    #[serde(rename = "web_link")]
    WebLink,
}

impl Default for RHashType {
    fn default() -> RHashType {
        Self::WebLink
    }
}

