/*
 * Box Platform API
 *
 * [Box Platform](https://box.dev) provides functionality to provide access to content stored within [Box](https://box.com). It provides endpoints for basic manipulation of files and folders, management of users within an enterprise, as well as more complex topics such as legal holds and retention policies.
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: devrel@box.com
 * Generated by: https://openapi-generator.tech
 */

/// ZipDownloadRequest : A request to create a `zip` archive to download



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ZipDownloadRequest {
    /// A list of items to add to the `zip` archive. These can be folders or files.
    #[serde(rename = "items")]
    pub items: Vec<crate::models::ZipDownloadRequestItemsInner>,
    /// The optional name of the `zip` archive. This name will be appended by the `.zip` file extension, for example `January Financials.zip`.
    #[serde(rename = "download_file_name", skip_serializing_if = "Option::is_none")]
    pub download_file_name: Option<String>,
}

impl ZipDownloadRequest {
    /// A request to create a `zip` archive to download
    pub fn new(items: Vec<crate::models::ZipDownloadRequestItemsInner>) -> ZipDownloadRequest {
        ZipDownloadRequest {
            items,
            download_file_name: None,
        }
    }
}


